/**
This file is auto-generated by the grok api command.
If you notice any changes, please push them to the repository.
Do not edit this file manually.
*/
import * as grok from 'datagrok-api/grok';
import * as DG from 'datagrok-api/dg';


export namespace funcs {
  export async function info(): Promise<void> {
    return await grok.functions.call('LinSysLab:Info', {});
  }

  /**
  Analyze a sparse matrix in COO triplet form
  */
  export async function analyzeCOO(Adf: DG.DataFrame , Ai: DG.Column , Aj: DG.Column , Av: DG.Column ): Promise<DG.DataFrame> {
    return await grok.functions.call('LinSysLab:AnalyzeCOO', { Adf, Ai, Aj, Av });
  }
}
